## Import Libraries

In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from keras.models import Sequential
from keras.layers import Dense, Activation
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
# Any results you write to the current directory are saved as output.

## Import Data Train

In [12]:
df = pd.read_csv('train.csv', dtype="float")

In [18]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
#X train and y train
X_train = df.iloc[:,1:].values/255.0
y_train = df.iloc[:,0].values[:,np.newaxis]
onehotencoder = OneHotEncoder(categories='auto')
y_train = onehotencoder.fit_transform(y_train).toarray()

In [24]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

## Multi Layer Perceptron

In [13]:
model = Sequential()
model.add(Dense(units=200, activation='relu', input_dim=784))
model.add(Dense(units=10, activation='softmax'))
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, validation_split=0.1, epochs=10, verbose=1)

Epoch 1/10
1182/1182 [==============================] - 14s 11ms/step - loss: 0.2774 - accuracy: 0.9178 - val_loss: 0.1597 - val_accuracy: 0.9493
Epoch 2/10
1182/1182 [==============================] - 10s 8ms/step - loss: 0.1255 - accuracy: 0.9633 - val_loss: 0.1348 - val_accuracy: 0.9600
Epoch 3/10
1182/1182 [==============================] - 9s 8ms/step - loss: 0.0892 - accuracy: 0.9742 - val_loss: 0.1103 - val_accuracy: 0.9676
Epoch 4/10
1182/1182 [==============================] - 8s 7ms/step - loss: 0.0689 - accuracy: 0.9801 - val_loss: 0.1017 - val_accuracy: 0.9710
Epoch 5/10
1182/1182 [==============================] - 9s 7ms/step - loss: 0.0549 - accuracy: 0.9842 - val_loss: 0.1006 - val_accuracy: 0.9719
Epoch 6/10
1182/1182 [==============================] - 9s 7ms/step - loss: 0.0432 - accuracy: 0.9875 - val_loss: 0.1059 - val_accuracy: 0.9724
Epoch 7/10
1182/1182 [==============================] - 9s 7ms/step - loss: 0.0352 - accuracy: 0.9895 - val_loss: 0.0985 - val_accuracy: 0.9748
Epoch 8/10
1182/1182 [==============================] - 8s 7ms/step - loss: 0.0292 - accuracy: 0.9917 - val_loss: 0.1060 - val_accuracy: 0.9736
Epoch 9/10
1182/1182 [==============================] - 9s 7ms/step - loss: 0.0246 - accuracy: 0.9932 - val_loss: 0.1057 - val_accuracy: 0.9760
Epoch 10/10
1182/1182 [==============================] - 8s 7ms/step - loss: 0.0204 - accuracy: 0.9942 - val_loss: 0.1155 - val_accuracy: 0.9736

## Import Data Test

In [14]:
df_test = pd.read_csv('test.csv', dtype="float")

875/875 [==============================] - 2s 2ms/step

In [25]:
df_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
X_test = df_test.values/255.0
y_pred = model.predict(X_test, verbose=1)
y_pred = np.argmax(y_pred, axis = 1)
pred = pd.DataFrame({"ImageId": range(1,len(y_pred)+1), "Label": y_pred})
pred.to_csv('results.csv', index=False, header=True)

875/875 [==============================] - 3s 3ms/step

In [5]:
#10 teratas dari hasil prediksi
pred.head(10)

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3
5        6      7
6        7      0
7        8      3
8        9      0
9       10      3

In [17]:
pred['Label'].value_counts()

1    3236
7    2867
2    2818
3    2815
0    2811
4    2775
6    2772
9    2736
8    2722
5    2448
Name: Label, dtype: int64